In [ ]:
import numpy
import ga

"""
The y=target is to maximize this equation ASAP:
    y = w1x1+w2x2+w3x3+w4x4+w5x5+6wx6
    where (x1,x2,x3,x4,x5,x6)=(4,-2,3.5,5,-11,-4.7)
    What are the best values for the 6 weights w1 to w6?
    We are going to use the genetic algorithm for the best possible values after a number of generations.
"""

# Inputs of the equation.
equation_inputs = [4,-2,3.5,5,-11,-4.7]

# Number of the weights we are looking to optimize.
num_weights = 6

"""
Genetic algorithm parameters:
    Mating pool size
    Population size
"""
sol_per_pop = 8
num_parents_mating = 4

# Defining the population size.
pop_size = (sol_per_pop,num_weights) # The population will have sol_per_pop chromosome where each chromosome has num_weights genes.
#Creating the initial population.
new_population = numpy.random.uniform(low=-4.0, high=4.0, size=pop_size)
print(new_population)

num_generations = 5
for generation in range(num_generations):
    print("Generation : ", generation)
    # Measing the fitness of each chromosome in the population.
    fitness = ga.cal_pop_fitness(equation_inputs, new_population)

    # Selecting the best parents in the population for mating.
    parents = ga.select_mating_pool(new_population, fitness, 
                                      num_parents_mating)

    # Generating next generation using crossover.
    offspring_crossover = ga.crossover(parents,
                                       offspring_size=(pop_size[0]-parents.shape[0], num_weights))

    # Adding some variations to the offsrping using mutation.
    offspring_mutation = ga.mutation(offspring_crossover)

    # Creating the new population based on the parents and offspring.
    new_population[0:parents.shape[0], :] = parents
    new_population[parents.shape[0]:, :] = offspring_mutation

    # The best result in the current iteration.
    print("Best result : ", numpy.max(numpy.sum(new_population*equation_inputs, axis=1)))

# Getting the best solution after iterating finishing all generations.
#At first, the fitness is calculated for each solution in the final generation.
fitness = ga.cal_pop_fitness(equation_inputs, new_population)
# Then return the index of that solution corresponding to the best fitness.
best_match_idx = numpy.where(fitness == numpy.max(fitness))

print("Best solution : ", new_population[best_match_idx, :])
print("Best solution fitness : ", fitness[best_match_idx])

[[ 1.05296407  1.72607068 -1.88090724  1.80660045 -2.89777063  0.84558545]
 [-1.97635494  1.62939118  3.65949092 -2.54028252  3.4473359   1.27104069]
 [-1.57688912 -0.95103816  2.95604759  1.67378859 -0.36662691 -3.21366804]
 [-1.43875313 -2.21860311  3.07279383 -0.67749989 -1.84103813  3.0981828 ]
 [-2.60797629 -0.23048762 -0.80787553 -1.23314044  3.39129158  0.19813441]
 [ 3.69617743  3.22782091 -1.78070164 -0.60564332  3.52831028 -0.9335268 ]
 [-3.27421094 -0.00662424  2.25932178  3.06837434  2.44053851 -3.44675571]
 [ 2.17998173 -3.80902238  0.4155707  -1.29898012  0.21350135 -0.86472156]]
Generation :  0
Best result :  44.77119774189849
Generation :  1
Best result :  44.77119774189849
Generation :  2
Best result :  54.61183625259211
Generation :  3
Best result :  54.798198281614994
Generation :  4
Best result :  58.20185147281008
Best solution :  [[[-1.43875313 -2.21860311  3.07279383  1.67378859 -2.29924515
   -3.21366804]]]
Best solution fitness :  [58.20185147]
